$ANSIBLE_VAULT;1.1;AES256
32623331613636376661646364653066653339303138323966326337323665393437653731656666
3561363832666431366163336630656239343333646463310a333963363539323130386338616535
61653539646334613364373465646662343138326166333533386330636531306361396237363432
3231306462353039650a373837613536666634383332643339653732666165613630353633633733
39613336623530666139646431613437626164333063333561396538633665633735303236303563
3162346466643661373437306338316232623861396363323434
