$ANSIBLE_VAULT;1.1;AES256
39386363373431396434376534613763616632623966383333373236636334333062343635303264
3630396636376230636565343864313539326232663132320a653762323539616263623562653963
65643638386632376263616331356434663664323362643463373334396639366436346664663362
3533666135663464630a346639663861656135366366353437666565636330306437383534633235
63646635353136376230383763336336616334636137363466366137366363636134386638376639
3265633533616334383039616638353964633165373437616430
