- name: configure jenkins server
  hosts: tag_Jenkins_Server
  become: true
  roles:
    - jenkins

- name: configure sonarqube server
  hosts: tag_SonarQube_Server
  become: true
  roles:
    - sonarqube
